lesson:
  size: 2
user:
  per_page: 10
category:
  per_page: 15
image: "img.jpg"
all_users: "all_users"
all_categories: "all_categories"
word:
  per_page: 15
  filter:
    learnt: "learnt"
    not_yet: "not_yet"
    all_word: "all_word"
