lesson:
  size: 2
user:
  per_page: 10
category:
  per_page: 15
image: "img.jpg"
all_users: "all_users"
all_categories: "all_categories"
word:
  per_page: 15
  filters:
    - all_words
    - learnt
    - not_yet
following:
  per_page: 10
follower:
  per_page: 10
activity:
  size: 10
  per_page: 10
